### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by Nelluk** [rivermeow/covid-vaccine-tools#1]
Great tool, thank you!

I had an idea for a bookmarklet that would open the RiteAid qualifier, fill out the form with my info, and hit the submit button, just to save that 10 seconds of time every time I am looking for appointments. When searching for ways to accomplish this I found your Reddit post. I'm very rusty on javascript so I thought I'd suggest this to you as a possible secondary bookmarklet to accompany your primary one.

**Comment by rivermeow** [comment]
Here you go: https://github.com/rivermeow/covid-vaccine-tools/blob/main/bookmarklets/riteaid-qualifier-fill.js

Edit the values as needed.  I've tested it in Chrome, Safari, and Firefox.  Firefox doesn't populate the zip code on the store search page but aside from that it works well.  Also, It can't open the page unfortunately so you'll have to do that first.

**Comment by Nelluk** [comment]
Works great, thank you so much!

**Comment by rivermeow** [comment]
They added a few new form fields so I've updated the bookmarklet.  Also, they're restricting it to childcare/education workers through the 20th.
